### PR TITLE
Specify build job rather than workflow.

### PR DESCRIPTION
**Pull request by Grumb1e**
Previously targeted entire workflow which caused pending status. Now targeting job specifically.

### CODE REVIEW

**Comment by Grumb1e** [comment]
Interesting. How does it distinguish two jobs with the same name from different workflows?

**Comment by netomi** [comment]
I fixed the name of the status check. The rules are explained here: https://otterdog.readthedocs.io/en/latest/reference/organization/repository/status-check/

In general, the name of the workflow is irrelevant, that is displayed in the UI but not relevant when setting the data.

I also tested the name that I changed and that makes the PR eligible to be merged.

**Comment by netomi** [comment]
yeah so we had cases where there have been multiple workflows with jobs names that are equal. In such cases the behavior is quite undefined afaict, you are advised to give unique job names.

The convention has not been designed by us, but we just use what GitHub reports back itself via its API.

**Review by dondunne — APPROVED** [review]

**Comment by Grumb1e** [comment]
Ah, I will keep that in mind then. Thank you for the info. : )

**Comment by netomi** [comment]
so in case you missed that, as the PR was approved by a PL, you can apply the changes yourself by adding `/otterdog merge` as a comment.

**Comment by Grumb1e** [comment]
Haha, my bad. I was just reading that bottom merge info and ignored the comments from the bot. Thank you for pointing that out. I totally missed it. : )

**Comment by netomi** [comment]
there was just a service outage around the time you added the comment, thats why it took a while to process it.

**Pull request merged**
