### PR TITLE
Create org.eclipse.osee Repository and Require Reviews

### PR DESCRIPTION
**Pull request by Grumb1e**

### CODE REVIEW

**Comment by netomi** [comment]
LGTM, why not name the repo simply osee?

I will add project leads as reviewers, once approved you can merge yourself.

Edit: I see that three is a repo on gerrit with exactly that name, do you intend to transfer that repo to GitHub?

**Comment by Grumb1e** [comment]
> LGTM, why not name the repo simply osee?

I believe reverse domain notation was decided on by the team many years in the past and has simply survived until today.

> I see that three is a repo on gerrit with exactly that name, do you intend to transfer that repo to GitHub?

Yes, but not in its entirety and only on a provisional basis at the moment. The intention was to only move over the Gerrit "dev" branch as a new GitHub "main" branch which would both perform garbage collection and rectify our unusual branch name. Additionally, it will likely take us some time to figure out the best way to utilize GitHub actions so we do not want to impact the current Gerrit repository in the mean time. Unfortunately, that means we are going to have to do another sync between the two repositories when we make the final swap.

**Comment by netomi** [comment]
ok ty for your explanation, then this PR makes sense.

**Comment by lucianovaglienti** [comment]
> > LGTM, why not name the repo simply osee?
> 
> I believe reverse domain notation was decided on by the team many years in the past and has simply survived until today.
> 
This might be a good time to talk about that, no? I think it might make sense going forward to just be osee.

**Comment by Grumb1e** [comment]
We can get a comment from the team leads when they are ready to review. My guess is that it will be vetoed because the naming convention is used for some of our other repositories and the fact that our directory naming structure inside the repository uses the same convention. Definitely a good conversation to have though.

**Review by david-w-miller — APPROVED** [review]
Looks good

**Pull request merged**
