### PR TITLE
Restore main branch protections

### PR DESCRIPTION
**Pull request by dondunne**

### CODE REVIEW

**Review by david-w-miller — APPROVED** [review]

**Comment by netomi** [comment]
fyi: you probably tried to push directly to the default branch but the branch protection rule did not permit it due to required status checks. This is a known issue with branch protection rules and you cant bypass that.

However, using rulesets would fix that. We set this up for another project like that: https://github.com/eclipse-zenoh/.eclipsefdn/blob/main/otterdog/eclipse-zenoh.jsonnet#L3

Might be an option for you as well. Other than that rulesets are offering the same as branch protection rules.

**Comment by netomi** [comment]
there is also some info about this added in the documentation: https://otterdog.readthedocs.io/en/latest/reference/organization/repository/ruleset/

**Comment by netomi** [comment]
another nice thing about rulesets is you can switch between audit and enforce mode, so allows you to easily disable it temporarily and then reenable it using the self-service.

**Pull request merged**
