### PR TITLE
Add FF merge and review policy to OSEE website repo config

### PR DESCRIPTION
**Pull request by jadenpuckett**

### CODE REVIEW

**Review by Grumb1e — APPROVED** [review]
🦔

**Comment by netomi** [comment]
you tried to add a branch protection rule in a format that is not supported. May I ask you where you got this snippet from? It looks a bit like the format the rulesets use when you export them to json.

I can update the config, but do you intend to add a branch protection rule or a ruleset?

**Comment by jadenpuckett** [comment]
Hello - Due to the limited otter dog documentation I was able to find for our team, I have just been pushing test commits to this repo to try and see what works. This commit is my best guess to try to enforce a 2 review rule on the Osee-website repo. I also am trying to enforce FF merge only. If you have any links to available otterdog documentation, that would help a bunch! Our team would love to learn up on how to define each of our repos configuration as code.

**Comment by netomi** [comment]
documentation is available at: https://otterdog.readthedocs.io/en/latest/reference/resource-format/

I will setup the rule for you so that you can see how it works.

**Comment by netomi** [comment]
So I updated the branch protection rule to

- requires linear history: what you tried to setup with ff only, this is the way that is configurable in GitHub, for that to work you either need to have squash or rebase merges be enabled for the repo
- required approvals is 2

Most of the settings are already coming from the default config, you can override settings as needed. There is also a playground at https://eclipse-osee.github.io/.eclipsefdn/playground/ to allow you to quickly play around with snippets prior to making a PR.

**Comment by netomi** [comment]
there is also the dashboard for all eclipse projects at https://otterdog.eclipse.org/index . From there you can see configurations of other projects as well. Some came up with already quite sophisticated versions.

I agree, there is an initial learning curve for the configuration format, but once you got the knack of it, its rather straight forward imho.

**Comment by jadenpuckett** [comment]
Thank you so much for the info! When navigating to the Otterdog docs from a Google search, our team ran into blank pages like this one: https://otterdog.readthedocs.io/en/latest/usage/ and didn't know if we should be expecting more within the "user guide" area. The url you provided takes us to the right spot and I see now where to navigate there. Thanks.

**Comment by netomi** [comment]
yeah there are still some empty spots in the documentation, but the reference guide should be quite complete and thats the relevant part for users.

**Comment by jadenpuckett** [comment]
Understood. Looking forward to becoming experts with this! Seems straight forward as now we have some information and docs to look at😀

**Comment by netomi** [comment]
an approval from a project lead would be required for applying the change.

**Review by david-w-miller — APPROVED** [review]

**Pull request merged**
