### PR TITLE
add OSEE_PACKAGE_REGISTRY_MANAGEMENT_BOT

### PR DESCRIPTION
**Pull request by lucianovaglienti**
Requesting to add OSEE_PACKAGE_REGISTRY_MANAGEMENT_BOT with permissions to write, read, and delete from the package's registry.

We wish to delete "development" containers using a workflow like so: 
https://github.com/eclipse-osee/org.eclipse.osee/blob/main/.github/workflows/clean-up.yml

### CODE REVIEW

**Comment by lucianovaglienti** [comment]
Also uh...let me know if I filled it out wrong, as I don't quite know what you want to put in the secret path.

**Comment by netomi** [comment]
I dont fully understand the need for an additional token. The documentation of the delete-packages action states that the standard GitHub token is used unless the repo does not have access to the package, which it should have imho.

Also I found this old ticket: https://github.com/actions/delete-package-versions/issues/57
that states that deleting packages of type "container" should be supported.

The error in the workflow that I have seen seems also a bit different:

```
Error: get versions API failed. Package not found.
```

So maybe the right package can not be found? I see that you use `packageName: osee-server`, but when looking at the available packages, they seem to be named like that: ` org.eclipse.osee/osee-server` ?

**Comment by lucianovaglienti** [comment]
Yeah... I've seen that ticket as well. I've tried a few different variations on the name i.e. eclipse-osee/org.eclipse.osee/osee-server/(merge-#)-merge, osee-server/(merge-#). None seem to work, and no one on the team seems to have the permissions to go manually remove them through the front door either.

I've also seen this ticket that suggests that there is some level of special permissions required:
https://github.com/actions/delete-package-versions/issues/74#issuecomment-1384919532

**Comment by netomi** [comment]
these are all the names of packages owned by the eclipse-osee org:

```
org.eclipse.osee/osee-postgres
org.eclipse.osee/maven-node
org.eclipse.osee/osee-server
org.eclipse.osee/osee-demo-server
org.eclipse.osee/osee-postgres/147-merge
org.eclipse.osee/osee-server/147-merge
org.eclipse.osee/osee-server/144-merge
org.eclipse.osee/osee-server/150-merge
org.eclipse.osee/osee-server/151-merge
org.eclipse.osee/osee-server/152-merge
org.eclipse.osee/osee-server/153-merge
org.eclipse.osee/osee-server/154-merge
```

got it with this query:

`curl -L   -H "Accept: application/vnd.github+json"    -H "X-GitHub-Api-Version: 2022-11-28"   "https://api.github.com/users/eclipse-osee/packages?package_type=container" | jq ".[].name" -r`

**Comment by lucianovaglienti** [comment]
hmmm alright I'll try doing a hardcode and seeing if that works... I'll be back if not. :)

**Comment by netomi** [comment]
I also checked and for these packages, the repo org.eclipse.osee has admin permissions, so should be able to delete them.

**Comment by lucianovaglienti** [comment]
Looks like that worked. Thank you @netomi :)

**Pull request closed without merging**
